### ISSUE TITLE
Failed to download lm-sensors and 

### ISSUE THREAD

**Issue by Goran58** [dragino/openwrt-bb-1407#3]
The site lm-sensors seems to be shutdown.
One solution is to download lm_sensors and i2c-tools from another site  before you build the SDK/firmware.

```
cd barrier_breaker/dl 

wget http://pkgs.fedoraproject.org/repo/pkgs/lm_sensors/lm_sensors-3.3.5.tar.bz2/da506dedceb41822e64865f6ba34828a/lm_sensors-3.3.5.tar.bz2

wget http://dev.gateworks.com/sources/i2c-tools-2013-12-15-r6204.tar.gz
```

**Comment by dragino** [comment]
Thanks and recommend to switch to the https://github.com/dragino/openwrt-cc-15.05 . which are the latest code for latest firmware.
