### ISSUE TITLE
fxs not currently able to build

### ISSUE THREAD

**Issue by smosel** [dragino/openwrt-bb-1407#4]
This does not seem to build currently for the `fxs` configuration.

Tested on both Ubuntu 16.04 LTS and Windows 10 WSL (Ubuntu), both fail at the same point:

`make[2]: *** No rule to make target 'package/feeds/packages/libxml2/host/compile', needed by 'package/feeds/telephony/asterisk-13.x/compile'.  Stop.
`

Updated `scripts/download.pl` to fetch linux kernel via https (ftp.kernel.org was shutdown in Jan 2017).

**Comment by dragino** [comment]
fix the build issue. change back to Asterisk 11
